apiVersion: v3
name: echo-chart
version: 1.0.5
description: Test chart for source-distributed plugin

# This plugin is distributed as source code in the OCI registry.
# Helm will download and compile it automatically.
plugins:
  - name: echo-render
    version: 0.1.3
    type: render/v1
    repository: oci://ghcr.io/scottrigby/ref-hip-chart-defined-plugins/plugins/echo-render
