apiVersion: v3
name: varsubst-chart
version: 1.0.5
description: An example Helm chart using the varsubst-render plugin
type: application

# Chart-defined plugins (processed sequentially in list order)
plugins:
  - name: varsubst-render
    type: render/v1
    repository: oci://ghcr.io/scottrigby/ref-hip-chart-defined-plugins/plugins/varsubst-render
    version: 0.1.3
